# Generated by Django 6.0.6 on 2026-07-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='date',
        ),
    ]
